const
    LOGIN = 'LOGIN',
    LOG_OUT = 'LOG_OUT',
    SET_LOGIN_RESULT_TO_STORE = 'SET_LOGIN_RESULT_TO_STORE',
    SET_LOADING = 'SET_LOADING',
    SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export default {
    LOGIN,
    LOG_OUT,
    SET_LOGIN_RESULT_TO_STORE,
    SET_LOADING,
    SET_IS_AUTHENTICATED,
    LOGIN_SUCCESS
};
