const SET_LOADING = 'SET_LOADING',
    FETCH_USERS = 'FETCH_USERS',
    DELETE_USER = 'DELETE_USER',
    SET_ERROR_TO_STORE = 'SET_ERROR_TO_STORE',
    CREATE_USER = 'CREATE_USER',
    SET_NEW_USER_TO_STORE = 'SET_NEW_USER_TO_STORE',
    UPDATE_SEARCH = 'UPDATE_SEARCH',
    TOGGLE_IS_APP_STARTED = 'TOGGLE_IS_APP_STARTED',
    SET_USERS_TO_STORE = 'SET_USERS_TO_STORE';

export default {
    SET_LOADING,
    SET_USERS_TO_STORE,
    FETCH_USERS,
    DELETE_USER,
    SET_NEW_USER_TO_STORE,
    CREATE_USER,
    SET_ERROR_TO_STORE,
    UPDATE_SEARCH,
    TOGGLE_IS_APP_STARTED
};
