const SET_LOADING = 'SET_LOADING',
    FETCH_USERS = 'FETCH_USERS',
    SET_ERROR_TO_STORE = 'SET_ERROR_TO_STORE',
    SET_IS_SUCCESS = 'SET_IS_SUCCESS',
    SET_NEW_USER_TO_STORE = 'SET_NEW_USER_TO_STORE',
    SET_USER_DETAILS_TO_STORE = 'SET_USER_DETAILS_TO_STORE',
    TOGGLE_IS_APP_STARTED = 'TOGGLE_IS_APP_STARTED',
    SET_USERS_TO_STORE = 'SET_USERS_TO_STORE';

export default {
    SET_LOADING,
    SET_USERS_TO_STORE,
    FETCH_USERS,
    SET_NEW_USER_TO_STORE,
    SET_IS_SUCCESS,
    SET_ERROR_TO_STORE,
    TOGGLE_IS_APP_STARTED,
    SET_USER_DETAILS_TO_STORE
};
